### ISSUE TITLE
Copy URL button is not working

### ISSUE THREAD

**Issue by falcaopetri** [koaning/calmcode-feedback#211]
Each course's pages (e.g. https://calmcode.io/course/args-kwargs/introduction) have a `Copy URL` button:

![image](https://github.com/koaning/calmcode-feedback/assets/8387736/eb72a160-61e3-4359-9b27-4e9320f9d516)

After interacting with it, I found out that:

1. The button is not currently working: devtool's console outputs `introduction:359 Uncaught ReferenceError: copy is not defined
    at HTMLButtonElement.onclick (introduction:359:293)`
2. It is only shown on screens smaller than `768px`. It looks like the button only shows up when the CSS rule below is active:

```css
@media (min-width: 768px)
.md\:inline-flex {
    display: inline-flex;
}
```
