### ISSUE TITLE
pytest gitlab-ci yml file: docker Error response from daemon: pull access denied for python3.6, repository does not exist or may require 'docker login'.

### ISSUE THREAD

**Issue by mpamey** [koaning/calmcode-feedback#29]
Hi, 

I had some trouble getting gitlab-ci to work with the .yml file.
Source: https://github.com/koaning/blackjack/blob/master/gitlab-ci.yml

Fix:
Add quotation marks around python:3.6
image: "python:3.6"

I got a nasty error when pulling up the docker image:
`docker Error response from daemon: pull access denied for python3.6, repository does not exist or may require 'docker login'.`

Adding the quotation marks resolved the error and ran the test smoothly.

**Comment by koaning** [comment]
Really? Huh. This is on my todolist to fix. Thanks for the heads up!

**Comment by koaning** [comment]
I've just checked the gitlab file for the calmcode project. 

```yml
image: python:3.6

stages:
  - unittest

test:
  stage: unittest
  script:
    - pip install -r requirements.txt
    - pytest
```

No quotes seem to be needed. Could you double check by running it again?
